# This is a basic workflow to help you get started with Actions

name: web-ai.studio

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
      - 'webapp/**'
      - '.github/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'webapp/**'
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build web-ai.studio
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: .npmrc
        run: mv .npmrc-github .npmrc
        working-directory: ./webapp

      - name: Build the app
        run: npm ci
        working-directory: ./webapp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_LOGIN_READ_TOKEN }}

      # Runs a single command using the runners shell
      - name: Build the app
        run: npm run build
        working-directory: ./webapp

      # Runs a set of commands using the runners shell
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./webapp/dist/web-ai.studio/browser

  deploy:
    needs: build
    name: Deploy web-ai.studio
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy
        id: deployment

        uses: actions/deploy-pages@v4
